# Vagrantfile
Vagrant.configure('2') do |config|
  config.vm.box = 'hfm4/centos7'

  config.vm.define :src do |c|
    c.vm.network 'private_network', ip: '192.168.33.10'
  end
  config.vm.define :dst do |c|
    c.vm.network 'private_network', ip: '192.168.33.11'
  end
  config.vm.provider 'virtualbox' do |v|
    v.customize ['modifyvm', :id, '--memory', '256']
  end
end
